### ISSUE TITLE
Ignore routes with underscore `_`

### ISSUE THREAD

**Issue by BryceRussell** [BryceRussell/astro-pages#7]
In Astro's page directory you can exclude a file/folder by appending underscore `_` to the name: https://docs.astro.build/en/guides/routing/#excluding-pages Although `astro-pages` allows you to ignore routes using globs, `astro-pages` should also follow Astro's standard and ignore routes prefixed with an underscore `_`

**Comment by florian-lefebvre** [comment]
Does such default glob look good? `glob: ["**.{astro,ts,js}", "!**/_*"]`

**Comment by florian-lefebvre** [comment]
I'll submit a pr 👍
